version: '3.2'

services:
  jsapp:
    container_name: jsapp
    restart: always
    volumes:
      - ./jsapp:/jsapp
      # - ./static:/jsapp/static
    build:
      context: .
      dockerfile: npm.Dockerfile
    command: /jsapp.command.sh


  # psql:
  #   image: postgres:9.6
  #   container_name: psql
  #   restart: always
  #   volumes:
  #     - ./.pgdata:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   environment:
  #     - DB_SERVER_HOST=psql
  #     - DB_SERVER_PORT=5432
  #     - DB_SERVER_HOST=psql
  #     - DB_SERVER_PORT=5432
  #     - POSTGRES_USER=aa
  #     - POSTGRES_PASSWORD=aa
  #     - POSTGRES_DB=aa

      
  # web:
  #   container_name: web
  #   restart: always
  #   build:
  #     context: .
  #   depends_on:
  #     - psql
  #     - jsapp
  #   volumes:
  #     - .:/web
  #   ports:
  #     - 8000:8000
  #     - 5678:8001
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DB_NAME=aa
  #     - DB_USER=aa
  #     - DB_USER_PASSWORD=aa
  #     - DB_HOST=psql
  #     - DB_PORT=5432
  #     - DJANGO_SETTINGS_MODULE=settings.dev
  #   command: bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"

