# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='media')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
