# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-13 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0002_auto_20181013_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='attachment',
            field=models.FileField(upload_to='works/'),
        ),
    ]
