# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-19 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0003_auto_20181013_1803'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachments',
            table='attachments',
        ),
    ]
