# Generated by Django 2.2.12 on 2020-06-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0005_attachments_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='feedback/')),
                ('comment', models.TextField()),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
