# Generated by Django 2.2.12 on 2020-06-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('attach', models.FileField(null=True, upload_to='clients/')),
            ],
            options={
                'db_table': 'client',
            },
        ),
    ]
