# Generated by Django 2.2.12 on 2020-06-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0006_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=2048, null=True)),
                ('attach', models.FileField(blank=True, null=True, upload_to='clients/')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('landing', 'Landing pages'), ('internet_shop', 'Internet shops'), ('corporate_site', 'Corporate sites'), ('other', 'Other')], max_length=14)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AlterField(
            model_name='attachments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
        migrations.AddField(
            model_name='attachments',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alex.Project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alex.Client'),
        ),
    ]
