# Generated by Django 2.2.12 on 2020-06-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alex', '0007_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('landing', 'Landing pages'), ('internet_shop', 'Internet shops'), ('corporate_site', 'Corporate sites'), ('other', 'Other')], max_length=14)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alex.Client'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attachments',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alex.Project'),
        ),
    ]
